id: 2926935389764e99aa738f7d2d6bda4e
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_498-Tantra_of_the_Blue-Clad_Vajrapani-v1
  language: en
  author: ''
  volume: {}
